# vim ft=yaml
# travis-ci.org definition for skfuzzy build, modified from scikit-image

# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python


#  The Travis python is set to 3.2 for all builds, since we use the default python for the 3.2 build and the anaconda python otherwise
python:
    - 3.2

env:
    - ENV="python=2.6 numpy=1.6"
    - ENV="python=2.7 numpy"
    - ENV="python=3.4 numpy"
    - ENV="python=3.5 numpy"

virtualenv:
    system_site_packages: true

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update

    # Python 3.2 is not supported by Miniconda, so we use the package manager for that run.
    # NumPy has a bug in python 3 that is only fixed in the latest version,
    #  hence the below wget of numpy/_import_tools.py from github.
    - if [[ $ENV == python=3.3* ]]; then
        sudo apt-get install python3-numpy;
        wget https://raw.githubusercontent.com/numpy/numpy/master/numpy/_import_tools.py -O /home/travis/virtualenv/python3.2_with_system_site_packages/lib/python3.2/site-packages/numpy/_import_tools.py;
        sudo apt-get install python3-scipy;
        travis_retry pip install cython flake8 six nose networkx matplotlib;
      else
        wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
        export PATH="$HOME/miniconda/bin:$PATH";
        hash -r;
        conda config --set always_yes yes;
        conda update conda;
        conda info -a;
        travis_retry conda create -n test $ENV six scipy pip flake8 nose networkx matplotlib;
        source activate test;
      fi
    - travis_retry pip install coveralls pillow

install:
    - tools/header.py "Dependency versions"
    - tools/build_versions.py
    - if [[ $ENV == python=2.6* ]]; then
        travis_retry conda install unittest2;
      fi
    - export PYTHONWARNINGS=all
    - python setup.py build_ext --inplace

script:
    # Run all tests with minimum dependencies
    - nosetests --exe -v skfuzzy

    # Run pep8 and flake tests
    - flake8 --exit-zero --exclude=test_*,six.py skfuzzy doc/examples

after_success:
    - if [[ $ENV == python=3.3* ]]; then
          coveralls;
      fi
